steps:
  - label: "Deploying backend to ${ENG_STATS_ENV}"
    command: "./bin/ci-deploy"
    agents:
      queue: default
    concurrency: 1
    concurrency_group: "eng-stats-deploy-${ENG_STATS_ENV}"
    plugins:
      - cultureamp/aws-assume-role#v0.1.0:
          role: "$ROLE_ARN"
      - docker-compose#v3.1.0:
          run: backend
          env:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_REGION=us-east-1
            - ENG_STATS_ENV
            - ROLE_ARN
            - AWS_DEFAULT_REGION
            - AWS_REGION
            - AWS_ACCOUNT_ID
            - STAGE
            - BASTION
            - EC2_KEY_NAME
            - DATABASE_LOCAL_PORT
            - DATABASE_NAME