steps:
  - label: "Deploying backend to ${ENG_STATS_ENV}"
    command: "/bin/chamber ${STACK} exec -- ./bin/ci-deploy"
    agents:
      queue: default
    concurrency: 1
    concurrency_group: "eng-stats-deploy-${ENG_STATS_ENV}"
    plugins:
      - cultureamp/aws-assume-role#v0.1.0:
          role: "$ROLE_ARN"
      - docker-compose#v3.1.0:
          run: backend
          env:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN
            - AWS_REGION
            - AWS_DEFAULT_REGION
            - ENG_STATS_ENV
            - ROLE_ARN
            - STACK
            - STAGE