steps:
  - label: "Staging"
    trigger: "blog-deploy"
    build:
      commit: "$BUILDKITE_COMMIT"
      message: "$BUILDKITE_MESSAGE"
      branch: "$BUILDKITE_BRANCH"
      env:
        AWS_REGION: "us-east-1"
        AWS_ACCOUNT_ID: "088746931051"
        ROLE_ARN: arn:aws:iam::088746931051:role/buildkite
        STAGE: "staging"
  - label: "Production"
    trigger: "blog-deploy"
    build:
      commit: "$BUILDKITE_COMMIT"
      message: "$BUILDKITE_MESSAGE"
      branch: "$BUILDKITE_BRANCH"
      env:
        AWS_REGION: "us-east-1"
        AWS_ACCOUNT_ID: "926179289874"
        ROLE_ARN: arn:aws:iam::926179289874:role/buildkite
        STAGE: "production"