steps:
  - label: "Staging"
    trigger: "blog-deploy"
    build:
      commit: "$BUILDKITE_COMMIT"
      message: "$BUILDKITE_MESSAGE"
      branch: "$BUILDKITE_BRANCH"
      env:
        AWS_REGION: "us-east-1"
        AWS_ACCOUNT_ID: "745453995866"
        ROLE_ARN: arn:aws:iam::745453995866:role/blog-staging-ci-role
        STAGE: "staging"
  - label: "Production"
    trigger: "blog-deploy"
    build:
      commit: "$BUILDKITE_COMMIT"
      message: "$BUILDKITE_MESSAGE"
      branch: "$BUILDKITE_BRANCH"
      env:
        AWS_REGION: "us-east-1"
        AWS_ACCOUNT_ID: "745453995866"
        ROLE_ARN: arn:aws:iam::755220514429:role/blog-prod-ci-role
        STAGE: "prod"