steps:
  - label: "Staging"
    trigger: "eng-stats-deploy"
    build:
      commit: "$BUILDKITE_COMMIT"
      message: "$BUILDKITE_MESSAGE"
      branch: "$BUILDKITE_BRANCH"
      env:
        AWS_REGION: "us-east-1"
        ROLE_ARN: arn:aws:iam::745453995866:role/eng-stats-staging-ci-role
        STAGE: "staging"
  - label: "Production"
    trigger: "eng-stats-deploy"
    build:
      commit: "$BUILDKITE_COMMIT"
      message: "$BUILDKITE_MESSAGE"
      branch: "$BUILDKITE_BRANCH"
      env:
        AWS_REGION: "us-east-1"
        ROLE_ARN: arn:aws:iam::755220514429:role/eng-stats-prod-ci-role
        STAGE: "prod"