steps:
  - label: "Staging"
    command: "yarn sls invoke local -f pipelines -s staging"
    env:
      AWS_REGION: "us-east-1"
      ROLE_ARN: arn:aws:iam::745453995866:role/eng-stats-staging-ci-role
      STACK: "engstats-staging"
      STAGE: "staging"
    plugins:
      - cultureamp/aws-assume-role#v0.1.0:
          role: arn:aws:iam::745453995866:role/eng-stats-staging-ci-role
      - docker-compose#v3.1.0:
          run: backend
          env:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN
            - AWS_REGION
            - ROLE_ARN
  - label: "Production"
    command: "yarn sls invoke local -f pipelines -s prod"
    env:
      AWS_REGION: "us-east-1"
      ROLE_ARN: arn:aws:iam::755220514429:role/eng-stats-prod-ci-role
      STACK: "engstats-prod"
      STAGE: "prod"
    plugins:
      - cultureamp/aws-assume-role#v0.1.0:
          role: arn:aws:iam::755220514429:role/eng-stats-prod-ci-role
      - docker-compose#v3.1.0:
          run: backend
          env:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN
            - AWS_REGION
            - ROLE_ARN
