steps:
  - block: "Run command"
    prompt: "Please select the account and enter the command you wish to execute"
    fields:
      - select: "Select Account Id"
        key: accountId
        required: true
        options:
          - label: "Staging"
            value: "745453995866"
          - label: "Production"
            value: "755220514429"
      - select: "Select Role"
        key: role
        required: true
        options:
          - label: "Staging"
            value: "arn:aws:iam::745453995866:role/eng-stats-staging-ci-role"
          - label: "Production"
            value: "arn:aws:iam::755220514429:role/eng-stats-prod-ci-role"
      - select: "Select Stage"
        key: stage
        required: true
        options:
          - label: "Staging"
            value: "staging"
          - label: "Production"
            value: "production"
  - label: "Running script"
    command: "yarn sls invoke local -f pipelines -s ${STAGE}"
    plugins:
      - acloudguru/metadata-env:
          keys:
            - role=AWS_ASSUME_ROLE_ARN
            - accountId=AWS_ACCOUNT_ID
            - stage=STAGE
      - acloudguru/aws-assume-role:
      - docker-compose#v2.0.0:
          run: backend
          env:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN
            - AWS_REGION=us-east-1
            - AWS_ACCOUNT_ID