steps:
  - label: "Staging"
    command: "/bin/chamber exec engstats-staging -- yarn sls invoke local -f pipelines -s staging"
    plugins:
      - cultureamp/aws-assume-role#v0.1.0:
          role: "$ROLE_ARN"
      - docker-compose#v3.1.0:
          run: backend
          env:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN
            - AWS_REGION
            - ENG_STATS_ENV
            - CHAMBER_KMS_KEY_ALIAS
            - ROLE_ARN
            - STACK
            - STAGE
  - label: "Production"
    command: "/bin/chamber exec engstats-prod -- yarn sls invoke local -f pipelines -s prod"
    plugins:
      - cultureamp/aws-assume-role#v0.1.0:
          role: "$ROLE_ARN"
      - docker-compose#v3.1.0:
          run: backend
          env:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN
            - AWS_REGION
            - ENG_STATS_ENV
            - CHAMBER_KMS_KEY_ALIAS
            - ROLE_ARN
            - STACK
            - STAGE