  steps:
  - label: "Testing stack build test-${BUILDKITE_BUILD_NUMBER}"
    agents:
      queue: default
    env:
      AWS_REGION: "us-east-1"
      AWS_ACCOUNT_ID: "335713476045"
      BUILDKITE_BUILD_NUMBER: ${BUILDKITE_BUILD_NUMBER}
      ROLE_ARN: "arn:aws:iam::335713476045:role/eng-stats-test-ci-role"
      STAGE: "test"
    command: "./bin/ci-test -s test"
    plugins:
      - cultureamp/aws-assume-role#v0.1.0:
          role: "arn:aws:iam::335713476045:role/eng-stats-test-ci-role"
      - docker-compose#v3.1.0:
          run: backend
          env:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN
            - AWS_REGION
            - AWS_ACCOUNT_ID
            - BUILDKITE_BUILD_NUMBER
            - STAGE
            - ROLE_ARN